/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThisSiteRouteImport } from './routes/this-site'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as NowRouteImport } from './routes/now'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing.index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'
import { Route as NotesSlugRouteImport } from './routes/notes.$slug'

const ThisSiteRoute = ThisSiteRouteImport.update({
  id: '/this-site',
  path: '/this-site',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/notes/$slug',
  path: '/notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/now': typeof NowRoute
  '/resume': typeof ResumeRoute
  '/this-site': typeof ThisSiteRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/notes/': typeof NotesIndexRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/now': typeof NowRoute
  '/resume': typeof ResumeRoute
  '/this-site': typeof ThisSiteRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/notes': typeof NotesIndexRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/now': typeof NowRoute
  '/resume': typeof ResumeRoute
  '/this-site': typeof ThisSiteRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/notes/': typeof NotesIndexRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/now'
    | '/resume'
    | '/this-site'
    | '/notes/$slug'
    | '/writing/$slug'
    | '/notes/'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/now'
    | '/resume'
    | '/this-site'
    | '/notes/$slug'
    | '/writing/$slug'
    | '/notes'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/now'
    | '/resume'
    | '/this-site'
    | '/notes/$slug'
    | '/writing/$slug'
    | '/notes/'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NowRoute: typeof NowRoute
  ResumeRoute: typeof ResumeRoute
  ThisSiteRoute: typeof ThisSiteRoute
  NotesSlugRoute: typeof NotesSlugRoute
  WritingSlugRoute: typeof WritingSlugRoute
  NotesIndexRoute: typeof NotesIndexRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/this-site': {
      id: '/this-site'
      path: '/this-site'
      fullPath: '/this-site'
      preLoaderRoute: typeof ThisSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/notes/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NowRoute: NowRoute,
  ResumeRoute: ResumeRoute,
  ThisSiteRoute: ThisSiteRoute,
  NotesSlugRoute: NotesSlugRoute,
  WritingSlugRoute: WritingSlugRoute,
  NotesIndexRoute: NotesIndexRoute,
  WritingIndexRoute: WritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
